require('dotenv').config()
const express = require('express')
const cors = require('cors')
const app = express()
const port = process.env.PORT

const loveQuotes: string[] = [
  "Tu es la lumière de ma vie et le soleil de mes jours.",
  "Avec toi, chaque jour est une aventure merveilleuse.",
  "Ton sourire illumine mon monde.",
  "Je t'aime plus que les mots ne peuvent l'exprimer.",
  "Mon cœur bat pour toi et toi seule.",
  "Ton amour est le plus beau cadeau de ma vie.",
  "Tu es mon âme sœur, ma meilleure amie, mon tout.",
  "Ton amour est mon refuge, mon paradis.",
  "Avec toi, j'ai trouvé ma raison de vivre.",
  "Chaque instant passé avec toi est un moment précieux.",
  "Ton amour rend ma vie complète.",
  "Tu es la mélodie qui fait danser mon cœur.",
  "Je suis tellement reconnaissant de t'avoir dans ma vie.",
  "Ton amour me donne des ailes.",
  "Chaque jour à tes côtés est un jour parfait.",
  "Tu es mon rêve devenu réalité.",
  "Avec toi, je me sens invincible.",
  "Ton amour est mon trésor le plus précieux.",
  "Je t'aime plus que tout au monde.",
  "Tu es ma source de bonheur.",
  "Ton sourire fait fondre mon cœur.",
  "Avec toi, je me sens chez moi.",
  "Tu es la meilleure chose qui me soit arrivée.",
  "Je suis fou de toi.",
  "Ton amour est ma force.",
  "Je te veux pour toujours à mes côtés.",
  "Tu es la raison pour laquelle je me lève chaque matin.",
  "Je t'aime de tout mon cœur.",
  "Tu es mon ange, mon amour.",
  "Avec toi, je suis la meilleure version de moi-même.",
  "Ton amour me rend meilleur chaque jour.",
  "Je suis chanceux de t'avoir dans ma vie.",
  "Tu es la personne la plus incroyable que je connaisse.",
  "Je t'aime plus que les étoiles dans le ciel.",
  "Tu es mon univers.",
  "Ton amour est mon guide.",
  "Je ne veux rien d'autre que toi.",
  "Ton sourire est mon soleil.",
  "Je suis perdu sans toi.",
  "Avec toi, tout est possible.",
  "Tu es mon tout.",
  "Ton amour est ma vie.",
  "Je t'aime plus que tout.",
  "Tu es mon trésor.",
  "Ton amour est mon bonheur.",
  "Je suis complet avec toi.",
  "Tu es mon cœur, mon âme.",
  "Je t'aime plus chaque jour.",
  "Ton amour est mon rêve.",
  "Avec toi, je suis heureux.",
  "Tu es ma raison d'être.",
  "Ton amour est ma paix.",
  "Je t'aime plus que les mots.",
  "Tu es ma lumière.",
  "Ton amour est mon tout.",
  "Je suis éperdument amoureux de toi.",
  "Tu es ma joie de vivre.",
  "Ton amour est mon espoir.",
  "Je t'aime à la folie.",
  "Tu es mon étoile.",
  "Ton amour est mon monde.",
  "Je suis à toi pour toujours.",
  "Tu es mon bonheur.",
  "Ton amour est ma lumière.",
  "Je t'aime plus que la vie.",
  "Tu es mon souffle.",
  "Ton amour est mon énergie.",
  "Je suis fou amoureux de toi.",
  "Tu es mon rêve éveillé.",
  "Ton amour est ma joie.",
  "Je t'aime d'un amour éternel.",
  "Tu es ma merveille.",
  "Ton amour est mon souffle.",
  "Je suis entièrement à toi.",
  "Tu es mon miracle.",
  "Ton amour est mon destin.",
  "Je t'aime infiniment.",
  "Tu es mon trésor caché.",
  "Ton amour est ma fierté.",
  "Je suis béni de t'avoir.",
  "Tu es mon amour éternel.",
  "Ton amour est mon inspiration.",
  "Je t'aime pour l'éternité.",
  "Tu es ma vie.",
  "Ton amour est mon ancre.",
  "Je suis amoureux de toi comme jamais.",
  "Tu es ma moitié.",
  "Ton amour est ma passion.",
  "Je t'aime plus que tout au monde.",
  "Tu es ma raison de sourire.",
  "Ton amour est mon rêve réalisé.",
  "Je suis chanceux de t'avoir.",
  "Tu es mon tout, mon univers.",
  "Ton amour est mon souffle de vie.",
  "Je t'aime plus que tout ce que je peux dire.",
  "Tu es ma lumière dans l'obscurité.",
  "Ton amour est mon plus grand trésor.",
  "Je suis tellement heureux avec toi.",
  "Tu es ma plus grande joie.",
  "Ton amour est mon refuge."
]


app.use(express.json())

app.listen(port, () => {
  console.log(`Server running on http://127.0.0.1:${port}`)
})

app.get('/', cors(), (req: any, res: any) => {
  const randomIndex: number = Math.floor(Math.random() * loveQuotes.length)
  res.status(200).json({"data":loveQuotes[randomIndex]})
})
